# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: postgresql
  encoding: unicode
  database: health_development
  pool: 5
  username: health
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: health_test
  pool: 5
  username: health
  password: password1
